/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#d9e3f4",
        "on-surface": "#191c1e",
        "on-secondary": "#ffffff",
        error: "#ba1a1a",
        "inverse-primary": "#b5c4ff",
        "tertiary-fixed-dim": "#68dba9",
        "on-primary-fixed": "#00174d",
        "on-secondary-container": "#596372",
        "on-tertiary-fixed-variant": "#005137",
        "on-background": "#191c1e",
        "inverse-on-surface": "#f0f1f3",
        "primary-fixed": "#dbe1ff",
        "surface-container-low": "#f3f4f6",
        "surface-tint": "#1353d8",
        "tertiary-container": "#006f4d",
        "secondary-fixed-dim": "#bdc7d8",
        "on-error-container": "#93000a",
        secondary: "#555f6d",
        background: "#f8f9fb",
        "on-secondary-fixed": "#121c28",
        "tertiary-fixed": "#85f8c4",
        "on-error": "#ffffff",
        "surface-variant": "#e1e2e4",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c3c5d7",
        "on-surface-variant": "#434654",
        "on-primary-container": "#d4dcff",
        surface: "#f8f9fb",
        "surface-container": "#edeef0",
        "surface-dim": "#d9dadc",
        "on-primary-fixed-variant": "#003dab",
        "inverse-surface": "#2e3132",
        "secondary-container": "#d6e0f1",
        outline: "#737686",
        "surface-bright": "#f8f9fb",
        "primary-fixed-dim": "#b5c4ff",
        "error-container": "#ffdad6",
        "primary-container": "#1a56db",
        "on-secondary-fixed-variant": "#3e4755",
        tertiary: "#005439",
        "on-tertiary-fixed": "#002114",
        "surface-container-high": "#e7e8ea",
        "on-tertiary-container": "#7ff2be",
        "on-primary": "#ffffff",
        primary: "#003fb1",
        "surface-container-highest": "#e1e2e4",
        "surface-container-lowest": "#ffffff",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.375rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
